stages:          
  - build
  - lint_format
  - migration
  - test
  - deploy

build-job:       
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
    - cp ${ENV_PROD} .env-prod
  script:
    - docker build -t lume-api-image .

Lint: 
  stage: lint_format
  script: 
  - docker run --rm --network LumeNetwork lume-api-image ruff check 

Format:
  stage: lint_format
  script: 
  - docker run --rm --network LumeNetwork lume-api-image ruff format --check


Migrations:
  stage: migration
  before_script:
    - cp ${ENV_PROD} .env-prod
  script: 
  - echo ${ENV_PROD}
  - docker run --rm --network LumeNetwork --env-file .env-prod lume-api-image  alembic upgrade head


Tests:
  stage: test
  script: 
  - docker run --rm --network LumeNetwork lume-api-image pytest tests/unit -v

deploy-job:
  stage: deploy  
  before_script:
    - cat "$ENV_PROD" > .env-prod  # Создаём .env-prod из переменной ENV_PROD
    - export $(cat .env-prod | xargs)  # Экспортируем переменные в окружение
  script:
    - docker compose up --build -d
    - docker exec lume_nginx nginx -s reload 

