stages:          
  - build
  - deploy

build-job:       
  stage: build
  before_script:
    - echo "$ENV" > .env
    - echo "$ENV_TEST" > .env-test
    - echo "$ENV_PROD" > .env-prod
  script:
    - docker build -t lume-api-image .

deploy-job:
  stage: deploy  
  script:
    - docker compose up -d 
