stages:          
  - build
  - deploy

build-job:       
  stage: build
  before_script:
    - cp ${ENV} ./.env
    - cp ${ENV_TEST} ./.env-test
    - cp ${ENV_PROD} ./.env-prod 
  script:
    - docker build -t lume-api-image .

deploy-job:
  stage: deploy  
  script:
    - docker compose up -d 
