stages:          
  - build
  - deploy

build-job:       
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
    - cp ${ENV_PROD} .env-prod
  script:
    - docker build -t lume-api-image .

deploy-job:
  stage: deploy  
  before_script:
    - echo ${ENV_PROD} > .env-prod  # Создаём .env-prod из переменной ENV_PROD
    - export $(cat .env-prod | xargs)  # Экспортируем переменные в окружение
  script:
    - ls -la  # Для отладки
    - cat .env-prod  # Для отладки
    - docker compose up -d
