stages:          
  - build
  - lint_format
  - migrations
  - test
  - deploy

build-job:       
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
  script:
    - docker build -t lume-api-image .

Lint: 
  stage: lint_format
  script: 
  - docker run --rm --network LumeNetwork lume-api-image ruff check 

Format:
  stage: lint_format
  script: 
  - docker run --rm --network LumeNetwork lume-api-image ruff format --check


Migrations:
  stage: migrations
  script: 
  - docker run --rm --network LumeNetwork lume-api-image alembic upgrade head


Tests:
  stage: test
  script: 
  - docker run --rm --network LumeNetwork lume-api-image pytest tests/unit -v

deploy-job:
  stage: deploy  
  script:
    - docker compose -f docker-compose-ci.yml up --build -d
    - docker exec lume_nginx nginx -s reload 
